name: ItStartsWithASpark
favicon: null
layout_spectrum: 0.0924
typography_spectrum: 0.31256
title: 'A big wave can be formed with even the tiniest of ripples. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#a4a4a4'
    - '#010101'
    - '#626262'
    - '#313131'
  brandStrength: 0.1942752383183688
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.7710110601037741
purpose: []
